version: '3.9'
services:
  nuxt:
    image: node:16.3.0-alpine3.12
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "80:3000"
    command: sh -c 'yarn generate && yarn start'