version: '3.9'
services:
  nginx:
    image: nginx:1.21
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo